### ISSUE TITLE
项目启动失败

### ISSUE THREAD

**Issue by Epiphany7725** [Xu22Web/tech-study-docker#13]
启动提示这个错误，更改了配置也不行

**Comment by Epiphany7725** [comment]
```
/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/app.ts:153:35 - error TS2493: Tuple type '[boolean, boolean, boolean]' of length '3' has no element at index '3'.

153       shared.schedule?.taskConfig[TaskType.PAPER] &&
                                      ~~~~~~~~~~~~~~

    at createTSError (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  diagnosticCodes: [ 2493 ]
}
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by Xu22Web** [comment]
查看下 taskConfig  '[boolean, boolean, boolean]'

**Comment by XATUCSJY** [comment]
> ```
> /root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:859
>     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
>            ^
> TSError: ⨯ Unable to compile TypeScript:
> src/app.ts:153:35 - error TS2493: Tuple type '[boolean, boolean, boolean]' of length '3' has no element at index '3'.
> 
> 153       shared.schedule?.taskConfig[TaskType.PAPER] &&
>                                       ~~~~~~~~~~~~~~
> 
>     at createTSError (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:859:12)
>     at reportTSError (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:863:19)
>     at getOutput (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:1077:36)
>     at Object.compile (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:1433:41)
>     at Module.m._compile (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:1617:30)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>     at Object.require.extensions.<computed> [as .ts] (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:1621:12)
>     at Module.load (node:internal/modules/cjs/loader:1119:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:960:12)
>     at Module.require (node:internal/modules/cjs/loader:1143:19) {
>   diagnosticCodes: [ 2493 ]
> }
>  ELIFECYCLE  Command failed with exit code 1.
> ```

老哥这个问题怎么解决的？
我的schedule.ts配置是这样的：
/**
 * @description 定时任务
 */
export type Schedule = {
  /**
   * @description 用户昵称
   */
  nick: string;
  /**
   * @description 用户token
   * @link {@link https://www.pushplus.plus/liaison.html 好友消息}
   */
  token: string;
  /**
   * @description 定时时间
   */
  cron: string;
  /**
   * @description 学习任务配置
   * @example [文章选读, 视听学习, 每日答题]
   */
  taskConfig: [boolean, boolean, boolean];
  /**
   * @description 刷新页面 cookie 的随机时间间隔，单位为分钟页面 cookie 过期时间大概是 4 个小时，设置小于 4 个小时都行
   * @example  [60, 120] 则表示随机取 60 ~ 120 分钟刷新一次
   */
  refreshCookieInterval: [number, number];
};

/**
 * @description 定时任务配置
 */
export const SCHEDULE_CONFIG: Schedule[] = [
  {
    nick: 'xxx',
    token: 'xxx',
    cron: '0 0 12 * * ?',
    taskConfig: [true, true, true],
    refreshCookieInterval: [60, 120],
  },
];

**Comment by warrenhoo** [comment]
我有同样的错误，老哥解决了吗

**Comment by Epiphany7725** [comment]
解决了 但是我忘了怎么弄了发自我的 iPhone在 2024年1月20日，11:21，warren ***@***.***> 写道：﻿
我有同样的错误，老哥解决了吗
