### ISSUE TITLE
pnpm start 启动报错

### ISSUE THREAD

**Issue by fgprodigal** [Xu22Web/tech-study-docker#8]
```
root@7eceed58f48c:~/tech-study-node# pnpm start
node[14]: ../src/node_platform.cc:68:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb7b3f0 node::Abort() [node]
 2: 0xb7b46e  [node]
 3: 0xbe9bde  [node]
 4: 0xbe9cc1 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 5: 0xb398eb node::InitializeOncePerProcess(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, node::ProcessFlags::Flags) [node]
 6: 0xb39f2b node::Start(int, char**) [node]
 7: 0x7f6b9ad81d90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7f6b9ad81e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xaba0fe _start [node]
Aborted (core dumped)
```

**Comment by yzhome** [comment]
我的也出错：
root@photon-machine [ ~ ]# docker-compose exec tech-study-docker bash
root@cb85e960669f:~/tech-study-node# pnpm start

> tech-study-node@1.0.0 start /root/tech-study-node
> ts-node bin/index.ts

/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: 猕 Unable to compile TypeScript:
bin/index.ts:5:24 - error TS2307: Cannot find module '../src/config/api' or its corresponding type declarations.

5 import API_CONFIG from '../src/config/api';
                         ~~~~~~~~~~~~~~~~~~~
bin/index.ts:6:24 - error TS2307: Cannot find module '../src/config/pup' or its corresponding type declarations.

6 import PUP_CONFIG from '../src/config/pup';
                         ~~~~~~~~~~~~~~~~~~~
bin/index.ts:7:25 - error TS2307: Cannot find module '../src/config/push' or its corresponding type declarations.

7 import PUSH_CONFIG from '../src/config/push';
                          ~~~~~~~~~~~~~~~~~~~~
bin/index.ts:8:43 - error TS2307: Cannot find module '../src/config/schedule' or its corresponding type declarations.

8 import { Schedule, SCHEDULE_CONFIG } from '../src/config/schedule';
                                            ~~~~~~~~~~~~~~~~~~~~~~~~
bin/index.ts:9:26 - error TS2307: Cannot find module '../src/config/study' or its corresponding type declarations.

9 import STUDY_CONFIG from '../src/config/study';
                           ~~~~~~~~~~~~~~~~~~~~~
bin/index.ts:10:24 - error TS2307: Cannot find module '../src/config/url' or its corresponding type declarations.

10 import URL_CONFIG from '../src/config/url';
                          ~~~~~~~~~~~~~~~~~~~

    at createTSError (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/root/tech-study-node/node_modules/.pnpm/ts-node@10.9.1_@types+node@18.11.18_typescript@4.9.4/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2307, 2307, 2307, 2307, 2307, 2307 ]
}
?𸁅LIFECYCLE?𸀠Command failed with exit code 1.
